---
- hosts: all
  become: true
  tasks:

  - name: install the apache2 and php package for Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install pip for python3
    apt:
     name:
       - python3-pip
