---
- hosts: all
  become: true
  tasks:

  - name: install the apache2, apache2 php package and pip-python3 for Debian or Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - python3-pip  
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

      
