
---
- hosts: all
  become: true
  tasks:

  - name: update apt repository
    apt:
     update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install Debian Multifunction Server services according CEHv9 book
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - bind9
        - ntp
        - samba
        - SNMPd
        - proftpd
        - postfix
      state: latest
    when: ansible_distribution == "Debian" 
