

- hosts: all
  become: true
  tasks:

  - name: update apt repository index
    apt:
     update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install the CEHv9 Multifunction Server
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - bind9
        - ntp
        - samba
        - SNMPd
        - proftpd
        - postfix
      state: latest
    when: ansible_distribution == "Debian"

     
