---


- hosts: [CEH_servers]
  become: true
  tasks:
    - name: create user
      user:
        name: alice
        password: alice1 | password_hash ('sha512')
        name: bob
        password: bob1 | password_hash ('sha512')
        name: tent
        password: tent1  | password_hash ('sha512')


- hosts: [CEH_servers]
  become: true
  tasks:

  - name: update apt repository
    apt:
     update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install Debian Multifunction Server services according CEHv9 book
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - bind9
        - ntp
        - samba
        - SNMPd
        - proftpd
        - postfix
      state: latest
    when: ansible_distribution == "Debian" 

