---
- hosts: all
  become: true
  tasks:

  - name: install the apache, apache php package on Debian or Ubuntu
    package:
      name:
        - "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

      
