---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install_updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Debian Servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"  

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package (Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"      


- hosts: file_servers
  become: true
  tasks:
  
  - name: install Samba packae
    package:
      name: samba
      state: latest
    when: ansible_distribution in ("Debian", "Ubuntu")

 



