---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install_updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Debian Servers
    tags: apache, apache2,Ubuntu,Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"  

  - name: copy defautl html file for site
    tags: apache,apache2,httpd
    copy: 
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package (Debian)
    tags: db,mariadb,Ubuntu,Debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"      


- hosts: file_servers
  become: true
  tasks:
  
  - name: install Samba package
    tags: samba
    package:
      name: samba
      state: latest
    when: ansible_distribution in ("Debian", "Ubuntu")

 



